spring:
    application:
        name: auth-service
    data:
        mongodb:
            uri: "mongodb+srv://jnexusadmin:jnexusadmin@cluster0.q6nnoki.mongodb.net/js_auth_service?retryWrites=true&w=majority"

server:
    port: 9030

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        hostname: localhost